#日志路径
log:
  file:
    path: ${log.path}ses-job-admin
    max-size: 128MB
    max-history: 180

server:
  servlet:
    context-path: /

### xxl-job, datasource
spring:
  datasource:
    url: jdbc:mysql://172.31.8.126:3306/xxl_job?useUnicode=true&amp;characterEncoding=UTF8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rede,1qaz2wsx

xxl:
  job:
    accessToken:
    i18n:
