#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
# DUBBO 集群配置
#dubbo:                                                                                                                  ##DUBBO配置
#  registry:                                                                                                             #注册中心
#    address: zookeeper://172.31.8.126:2181?backup=172.31.8.126:2182,172.31.8.126:2183
## DUBBO 单节点配置
dubbo:
  registry: #注册中心
    address: zookeeper://172.31.8.126:2181
  metadata-report:
    address: zookeeper://172.31.8.126:2181
spring:                                                                                                                 #spring config
  http:                                                                                                                 #上传配置
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://172.31.8.126:3306/operation?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rede,1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet:                                                                                                #监控页面的用户名和密码 以及页面地址
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.8.126:7000
        - 172.31.8.126:7001
        - 172.31.8.126:7002
        - 172.31.8.126:7003
        - 172.31.8.126:7004
        - 172.31.8.126:7005
  swagger:                                                                                                              #swagger在线文档配置
    enabled: true                                                                                                       #是否启用swagger
    group:
      sign-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 1.Sign-API                                                                                          #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: ROS Sign接口                                                                                              #api组的标题，会在swagger-ui的标题处显示
        description: 用户登录注销创建操作                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.mobile.rps
        path-regex: /sign/token/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      EntrustOrder-api:
        #用户组api，可以配置多个组
        group-name: 2.EntrustOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: 委托单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
        descrtion: 委托单相关接口
        #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.mobile.rps
        path-regex: /entrust/order/.*
        #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      OutWhOrder-api:
          #用户组api，可以配置多个组
          group-name: 3.OutWhOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
          title: 出库单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
          descrtion: 出库单相关接口
          #api组的描述，会在swagger-ui的描述中显示
          base-package: com.redescooter.ses.mobile.rps
          path-regex: /out/wh/order/.*
          #匹配到本组的api接口，匹配uri，可以用用正则表达式
          path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
          version: v1.2.1                                                                                                 #Api版本
          license: RedE 公司内部传阅                                                                                        #授权协议
          license-url: '#'                                                                                                #授权协议地址
          terms-of-service-url:                                                                                           #服务条款地址
          contact:                                                                                                        #文档联系人
            name: 李加廷                                                                                                   #联系人名字
            email: jerry@redescooter.com                                                                                  #联系人邮箱
            url: https://github.com/mrjerryli

      QcTemplate-api:
          #用户组api，可以配置多个组
          group-name: 4.QcOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
          title: 质检单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
          descrtion: 质检单相关接口
          #api组的描述，会在swagger-ui的描述中显示
          base-package: com.redescooter.ses.mobile.rps
          path-regex: /qc/order/.*
          #匹配到本组的api接口，匹配uri，可以用用正则表达式
          path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
          version: v1.2.1                                                                                                 #Api版本
          license: RedE 公司内部传阅                                                                                        #授权协议
          license-url: '#'                                                                                                #授权协议地址
          terms-of-service-url:                                                                                           #服务条款地址
          contact:                                                                                                        #文档联系人
            name: 李加廷                                                                                                   #联系人名字
            email: jerry@redescooter.com                                                                                  #联系人邮箱
            url: https://github.com/mrjerryli

      InWhOrder-api:
          #用户组api，可以配置多个组
          group-name: 5.InWhOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
          title: 入库单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
          descrtion: 入库单相关接口
          #api组的描述，会在swagger-ui的描述中显示
          base-package: com.redescooter.ses.mobile.rps
          path-regex: /in/wh/order/.*
          #匹配到本组的api接口，匹配uri，可以用用正则表达式
          path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
          version: v1.2.1                                                                                                 #Api版本
          license: RedE 公司内部传阅                                                                                        #授权协议
          license-url: '#'                                                                                                #授权协议地址
          terms-of-service-url:                                                                                           #服务条款地址
          contact:                                                                                                        #文档联系人
            name: 李加廷                                                                                                   #联系人名字
            email: jerry@redescooter.com                                                                                  #联系人邮箱
            url: https://github.com/mrjerryli

      CombinOrder-api:
          #用户组api，可以配置多个组
          group-name: 6.CombinOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
          title: 组装单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
          descrtion: 组装单相关接口
          #api组的描述，会在swagger-ui的描述中显示
          base-package: com.redescooter.ses.mobile.rps
          path-regex: /combination/order/.*
          #匹配到本组的api接口，匹配uri，可以用用正则表达式
          path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
          version: v1.2.1                                                                                                 #Api版本
          license: RedE 公司内部传阅                                                                                        #授权协议
          license-url: '#'                                                                                                #授权协议地址
          terms-of-service-url:                                                                                           #服务条款地址
          contact:                                                                                                        #文档联系人
            name: 李加廷                                                                                                   #联系人名字
            email: jerry@redescooter.com                                                                                  #联系人邮箱
            url: https://github.com/mrjerryli

      RpsHome-api:
          #用户组api，可以配置多个组
          group-name: 7.RpsHome-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
          title: RPS首页管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
          descrtion: RPS首页相关接口
          #api组的描述，会在swagger-ui的描述中显示
          base-package: com.redescooter.ses.mobile.rps
          path-regex: /home/.*
          #匹配到本组的api接口，匹配uri，可以用用正则表达式
          path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
          version: v1.2.1                                                                                                 #Api版本
          license: RedE 公司内部传阅                                                                                        #授权协议
          license-url: '#'                                                                                                #授权协议地址
          terms-of-service-url:                                                                                           #服务条款地址
          contact: #文档联系人
            name: 李加廷                                                                                                   #联系人名字
            email: jerry@redescooter.com                                                                                  #联系人邮箱
            url: https://github.com/mrjerryli


oss:                                                                                                                    #阿里oss上传
  #oss 使用http、https请求方式
  protocol: HTTPS

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-mobile-rps-group
  registry:
    type: zk
    zk:
      server-addr: 172.31.8.126:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 172.31.8.126:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-mobile-rps-group: default
  client:
    rm:
      report-success-enable: false
